M48
; DRILL file {KiCad 9.0.6-1.fc43} date 2025-12-17T22:37:08-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-17T22:37:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-1.fc43
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X117.0Y-142.0
X117.5Y-61.0
X193.5Y-61.5
X193.5Y-141.5
M30
